server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location ~ ^/api/teams/?$ {
    rewrite ^ /teams break;
    proxy_pass http://stat-api-server:${STAT_API_SERVER_PORT};
  }

  location ~ ^/api/batting/?$ {
    rewrite ^ /batting break;
    proxy_pass http://stat-api-server:${STAT_API_SERVER_PORT};
  }

  location ~ ^/api/simulate/?$ {
    rewrite ^ /simulate break;
    proxy_pass http://game-simulation:${GAME_SIMULATION_PORT};
  }

  location ~ ^/api/optimize/?$ {
    rewrite ^ /optimize break;
    proxy_pass http://game-simulation:${GAME_SIMULATION_PORT};
  }

  location /api/ {
    return 404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
