FROM node:20-alpine AS frontend-builder

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./
RUN npm run build

FROM nginx:1.27.0-alpine AS runner

COPY gateway/default.conf /etc/nginx/templates/default.conf.template
COPY --from=frontend-builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
